# Configuration file for all scripts
# All file paths are relative to the parent script directory, unless otherwise stated

# spectrum_fit.py config file
---
# Variables for training the network
training:
  # File number to save decoder progress
  decoder-save: 3
  # File number to save encoder progress
  encoder-save: 3
  # File number to load decoder state
  decoder-load: 3
  # File number to load encoder state
  encoder-load: 0
  # Number of epochs to train for
  epochs: 100
  # Learning rate for training
  learning-rate: 0.0002
  # File name for decoder model to load
  decoder-name: 'Decoder V2'
  # File name for encoder model to load
  encoder-name: 'Encoder V3'
  # Path to the configuration files for the encoder and decoder
  network-configs-directory: '../network_configs/'
# File location for different datasets
data:
  # Path to the spectra for decoder training
  decoder-data-path: '../data/synth_spectra.npy'
  # Path to the parameters for supervised decoder training
  decoder-parameters-path: '../data/synth_params.npy'
  # Path to the spectra for encoder training
  encoder-data-path: '../data/preprocessed_spectra.npy'
  # Path to the parameters if using supervised learning for the encoder (not required)
  encoder-parameters-path: '../data/nicer_bh_specfits_simplcut_ezdiskbb_freenh.dat'
  # Path to the directory of spectra fits files
  spectra-directory: '../../../Documents/Nicer_Data/spectra/'
# Model for the network to learn
model:
  # Number of free parameters
  parameters-number: 5
  # Xspec model to use
  model-name: 'tbabs(simplcutx(ezdiskbb))'
  # Name of custom model that has to be loaded, can be empty
  custom-model-name: 'simplcutx'
  # Directory to custom model, can be empty
  model-directory: '../../../Documents/Xspec_Models/simplcutx'
  # Which model parameter indices to take the log of
  log-parameters:
    - 0
    - 2
    - 3
    - 4
  # Index starting from 1 and value for each fixed parameter
  fixed-parameters:
    - # First fixed parameter
      - 4 # Index
      - 0 # Value
    - # Second fixed parameter
      - 5
      - 100
  # Default free parameter values, can be empty if default performance measurement isn't required
  default-parameters:
    - 1
    - 2.5
    - 0.02
    - 1
    - 1
  # Model parameter names for displaying on plots
  parameter-names:
    - 'nH'
    - '$\Gamma$'
    - 'FracSctr'
    - '$T_{max}$'
    - 'Norm'
# Directory locations for different outputs
output:
  # Path to the parameters predictions generated by the encoder
  parameter-predictions-path: '../data/parameter_predictions.csv'
  # Directory to save network training states
  network-states-directory: '../model_states/'
  # Directory to save plots
  plots-directory: '../plots/'
  # Directory for passing data to/from multiprocessing workers
  worker-directory: '../data/worker/'

# data_preprocessing.py config file
---
# File location for different datasets
data:
  # Path to the directory of spectra fits files
  # Should be the same as for spectrum_fit.py
  spectra-directory: '../../../Documents/Nicer_Data/spectra/'
  # spectra-directory: '../data/synth_spectra/'
  # Path to the directory of background fits files + background file location in spectrum fits file
  background-directory: '../../../Documents/Nicer_Data/spectra/'
  # background-directory: '../'
  # Path to the parameters, only required for supervised learning + data augmentation
  parameters-path: '../data/nicer_bh_specfits_simplcut_ezdiskbb_freenh.dat'
  # parameters-path: '../data/synth_params.npy'
# File location for outputs
output:
  # Path to the outputted spectra
  processed-path: '../data/preprocessed_spectra.npy'
  # processed-spectra-path: '../data/synth_spectra.npy'
augmentation:
  # Number of background scaling augmentations to do
  augmentation_number: 0

# synthesize_spectra.py config file
---
# Variables for synthesizing spectra
synthesize:
  # If previous synthetic data should be removed
  clear-spectra: False
  # Number of synthetic data to try to generate, real number will be less due to bad data cleaning
  synthetic-number: 100000
  # Number of spectra to generate before cleaning,
  # useful as the program has a bug where it will get stuck,
  # resulting in a loss of progress for the current batch
  spectra-per-batch: 100
  # Number of fake spectra to generate per background, lower is better but slower
  fake-per-background: 100
# File locations for outputs
# All paths are relative to the parent folder due to string overflows in fits files
data:
  # Path to the directory of spectra fits files
  # Should be the same as for spectrum_fit.py
  spectra-directory: '../../spectra/'
  # Path to the spectra names file, leave empty if this doesn't exist,
  # file names in spectra-directory will be used instead
  # Should be the same as for spectrum_fit.py
  spectra-names-file: '../data/nicer_bh_specfits_simplcut_ezdiskbb_freenh.dat'
# Model to base the synthetic spectra off
model:
  # Xspec model to use
  model-name: 'tbabs(simplcutx(ezdiskbb))'
  # Name of custom model that has to be loaded, can be empty
  # Should be the same as for spectrum_fit.py
  custom-model-name: 'simplcutx'
  # Directory to custom model, can be empty
  # Should be the same as for spectrum_fit.py
  model-directory: '../../../Documents/Xspec_Models/simplcutx'
  # Index starting from 1 and value for each fixed parameter
  # Should be the same as for spectrum_fit.py but as a dictionary
  fixed-parameters:
    4: 0
    5: 100
  # Parameter index, starting from 1, lower limit, upper limit,
  # and if the parameter should be logarithmically distributed for all free parameters
  parameter-limits:
    - # First free parameter
      id: 1 # Index from 1
      low: 0.005 # Lower limit
      high: 75 # Upper limit
      log: True # If logarithmically distributed
    -
      id: 2
      low: 1.3
      high: 4
      log: False
    -
      id: 3
      low: 0.001
      high: 1
      log: True
    -
      id: 6
      low: 0.025
      high: 4
      log: True
    -
      id: 7
      low: 0.01
      high: 10000000000
      log: True
# Directory locations for different outputs
output:
  # Path to the directory to output synthetic spectra fits files
  synthetic-directory: '../data/synth_spectra/'
  # Path to save the corrected and normalized spectra file
  synthetic-data: '../data/synth_spectra.npy'

# network_optimizer.py config file
---
# Optimization parameters
optimization:
  # If continuing from previous optimization process
  load: False
  # If optimization progress should be saved
  save: True
  # Number of epochs to train for
  epochs: 50
  # Number of trials to try
  trials: 30
  # Minimum number of trials before pruning can happen
  pruning-minimum-trials: 5
  # File name for the network to optimize
  name: 'Decoder V2'
  # Path to the configuration files for the encoder and decoder
  # Should be the same as for spectrum_fit.py
  network-configs-directory: '../network_configs/'
  # Which model parameter indices to take the log of
  # Should be the same as for spectrum_fit.py
  log-parameters:
    - 0
    - 2
    - 3
    - 4
# File location for different datasets
data:
  # Path to the spectra for training
  spectra-path: '../data/preprocessed_spectra.npy'
  # spectra-path: '../data/synth_spectra.npy'
  # Path to parameters if using supervised learning
  parameters-path: '../data/nicer_bh_specfits_simplcut_ezdiskbb_freenh.dat'
  # parameters-path: '../data/synth_params.npy'
# Directory locations for outputs
output:
  # Directory to save network optimization states
  network-states-directory: '../model_states/'
